name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.11
        auto-update-conda: true
        auto-activate-base: false

    - name: Create and activate project-specific environment
      run: |
        conda create --name myprojectenv python=3.11 -y
        echo "conda activate myprojectenv" >> $GITHUB_ENV
    - name: Install dependencies
      run: |
        conda install flake8 pytest -y
        # Add any other dependencies here, e.g., conda install numpy pandas
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
